name = "chess-problems-staging"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "chess-problems-db"
database_id = "3c2462f4-e342-48a8-807a-f40616066b02"

[[d1_databases]]
binding = "STATS_DB"
database_name = "chess-problems-db-staging"
database_id = "ea49673e-d115-4169-bce9-b74f4f632aae"
